CREATE DATABASE /*!32312 IF NOT EXISTS*/`mydays` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `mydays`;

CREATE TABLE User (id BIGINT NOT NULL AUTO_INCREMENT, device_type INT NOT NULL,device_num VARCHAR(100),state INT NOT NULL,nickname VARCHAR(100) NOT NULL,PRIMARY KEY (id));